### ISSUE TITLE
Criação da pagina sobre

### ISSUE THREAD

**Issue by MarceloSeabra** [JogarSo/github-master#3]
Você poderia criar uma pagina sobre ? Agradeço.

**Comment by JogarSo** [comment]
Pagina esta em produção.

**Comment by MarceloSeabra** [comment]
Obrigado, estou aguardando.
________________________________
De: JogarSo <notifications@github.com>
Enviado: domingo, 18 de agosto de 2019 20:10
Para: JogarSo/github-master <github-master@noreply.github.com>
Cc: Marcelo Viana Magalhães Seabra <marcelo.vms@outlook.com>; Author <author@noreply.github.com>
Assunto: Re: [JogarSo/github-master] Criação da pagina sobre (#3)


Pagina esta em produção.

**Comment by JogarSo** [comment]
Poderia colocar o telefone  no site @
